owner: petebachant
name: boom-benchmarking
title: Benchmarking BOOM database options
description:
git_repo_url: https://github.com/petebachant/boom-benchmarking
questions:
  - Which configuration is faster to insert ~1 million alerts?
  - Which configuration is faster to query ~1 million alerts?
  - Which configuration is faster to run a cross-match query?
  - Which configuration is faster to run a cone search?
  - Which configuration is faster to run a set of filters on a single alert?
dependencies:
  - tar
  - gunzip
  - curl
  - docker
  - uv
environments:
  py:
    kind: uv-venv
    python: "3.12.4"
    path: envs/py.txt
    prefix: .venv
  duckdb:
    path: envs/duckdb.txt
    kind: uv-venv
    prefix: .venv-duckdb
    python: "3.12.4"
pipeline:
  stages:
    get-ztf-data:
      kind: shell-script
      script_path: scripts/download-ztf-data.sh
      environment: _system
      outputs:
        - path: data/ztf_public_20250614.tar.gz
          delete_before_run: false
          storage:
        - path: data/ztf_public_20250614
          delete_before_run: true
          storage:
    extract-ned-data:
      kind: shell-command
      command: gunzip -k data/kowalski.NED.json.gz
      environment: _system
      inputs:
        - data/kowalski.NED.json.gz
      outputs:
        - path: data/kowalski.NED.json
          delete_before_run: true
          storage:
    inspect-alert:
      kind: jupyter-notebook
      notebook_path: notebooks/inspect-alert.ipynb
      environment: py
      inputs:
        - data/kowalski.NED.json
        - data/ztf_public_20250614
      html_storage: git
      executed_ipynb_storage:
      cleaned_ipynb_storage:
    benchmark-mongo:
      kind: jupyter-notebook
      notebook_path: notebooks/benchmark-mongo.ipynb
      environment: py
      inputs:
        - docker-compose.yaml
      outputs:
        - path: results/mongo.json
          storage: git
      html_storage: git
      executed_ipynb_storage:
      cleaned_ipynb_storage:
    benchmark-pg:
      kind: jupyter-notebook
      notebook_path: notebooks/benchmark-pg.ipynb
      environment: py
      inputs:
        - docker-compose.yaml
        - envs/Dockerfile.pg-q3c
      outputs:
        - path: results/postgres.json
          storage: git
      html_storage: git
      executed_ipynb_storage:
      cleaned_ipynb_storage:
    summarize:
      kind: jupyter-notebook
      notebook_path: notebooks/summarize.ipynb
      environment: py
      inputs:
        - results/mongo.json
        - results/postgres.json
      html_storage: git
      executed_ipynb_storage: git
      cleaned_ipynb_storage:
datasets:
  - path: data/kowalski.NED.json.gz
    title: NED alert archive from Kowalski
  - path: data/ztf_public_20250614.tar.gz
    title: ZTF public alert archive for June 14, 2025
    imported_from:
      url: https://ztf.uw.edu/alerts/public/ztf_public_20250614.tar.gz
notebooks:
  - path: notebooks/summarize.ipynb
    title: Summarize results
    description: >
      This notebook summarizes the results of the MongoDB and PostgreSQL
      benchmarks.
      It compares the performance of both databases in terms of insertion
      speed,
      query speed, and filtering capabilities.
  - path: notebooks/benchmark-mongo.ipynb
    title: Benchmark MongoDB
    description: >
      This notebook benchmarks the performance of MongoDB for inserting
      and querying alerts.
  - path: notebooks/benchmark-pg.ipynb
    title: Benchmark PostgreSQL
    description: >
      This notebook benchmarks the performance of PostgreSQL for inserting
      and querying alerts.
  - path: notebooks/inspect-alert.ipynb
    title: Inspect alert structure
    description: >
      This notebook shows the structure of the ZTF and NED alerts.
    stage: inspect-alert
showcase:
  - notebook: notebooks/summarize.ipynb
