services:
  mongo:
    image: mongo:8.0
    hostname: mongo
    ports:
      - "27018:27017"
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      start_period: 20s
