services:
  mongo:
    image: mongo:8.0
    hostname: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      start_period: 20s
  postgres:
    image: pg16-q3c-boom
    hostname: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    build:
      context: ./envs
      dockerfile: Dockerfile.pg-q3c
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
